authorization {
  users = [
    {
      user: "app_web"
      password: "app_web_dev"
      permissions: {
        publish: [
          "svc.vote.submit.*",
          "svc.vote.status.*",
          "svc.vote.results.*",
          "svc.vote.monitor.>"
        ]
        subscribe: [
          "_INBOX.>",
          "evt.vote.results.*"
        ]
      }
    },
    {
      user: "app_ios"
      password: "app_ios_dev"
      permissions: {
        publish: [
          "svc.vote.submit.*",
          "svc.vote.status.*",
          "svc.vote.results.*"
        ]
        subscribe: [
          "_INBOX.>",
          "evt.vote.results.*"
        ]
      }
    },
    {
      user: "app_backend"
      password: "app_backend_dev"
      permissions: {
        publish: [
          "svc.vote.>",
          "vote.cmd.>",
          "vote.event.>",
          "vote.result.>",
          "evt.vote.results.>",
          "$JS.API.>",
          "$JS.ACK.>",
          "$JS.FC.>",
          "$KV.>",
          "$kv.>",
          "_INBOX.>"
        ]
        subscribe: [
          "svc.vote.>",
          "vote.cmd.>",
          "vote.event.>",
          "vote.result.>",
          "evt.vote.results.>",
          "$JS.API.>",
          "$JS.ACK.>",
          "$JS.FC.>",
          "$KV.>",
          "$kv.>",
          "_INBOX.>"
        ]
      }
    },
    {
      user: "ops"
      password: "ops_dev"
      permissions: {
        publish: [">"]
        subscribe: [">"]
      }
    }
  ]
}
